### ISSUE TITLE
Can not reference to Microsoft.Extensions.Primitives.dll

### ISSUE THREAD

**Issue by jiabiao** [getgauge/gauge-dotnet#24]
It can add any other third-party nuget packages. But for Microsoft.Extensions.Primitives,  it will throw the System.IO.FileLoadException from Gauge.Dotnet.GaugeListener.

reproduct steps:
```cmd
gauge init dotnet
dotnet add package Microsoft.Extensions.Primitives --version 2.1.1
dotnet restore
gauge run
```

![image](https://user-images.githubusercontent.com/1818225/43256525-89325b82-90ff-11e8-8ed0-b111e9bb29ed.png)

**Comment by jiabiao** [comment]
I guess this is beacuse gauge-dotnet already referenced to Microsoft.Extensions.Primitives 2.0.0
![image](https://user-images.githubusercontent.com/1818225/43298636-64b80920-9189-11e8-9d64-075de1a30a42.png)

**Comment by BugDiver** [comment]
@jiabiao After some investigation, I found out that we reference a package named `NLog.Extensions.Logging` which refers to `Microsoft.Extensions.Primitives.dll`.
https://github.com/getgauge/gauge-dotnet/blob/0f957027ce011552b032f4d239a8a3ceb60a68a0/src/Gauge.Dotnet.csproj#L34

We can get rid of `NLog.Extensions.Logging` since it is not used anywhere.

**Comment by BugDiver** [comment]
The fix should be available in nightly >= 01-08-2018.

**Comment by sguptatw** [comment]
Verified in
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
dotnet (0.1.1.nightly-2018-08-01)
```
