### ISSUE TITLE
Issue cleanup

### ISSUE THREAD

**Issue by mpekurny** [getgauge/gauge-dotnet#240]
I was just wondering if some of the issues in this repo could get cleaned up? Several of them are old or actually addressed.

For example, these I believe are all addressed
https://github.com/getgauge/gauge-dotnet/issues/204
https://github.com/getgauge/gauge-dotnet/issues/203
https://github.com/getgauge/gauge-dotnet/issues/199
https://github.com/getgauge/gauge-dotnet/issues/151
https://github.com/getgauge/gauge-dotnet/issues/30

There might be some others that could be closed, but I am pretty sure the ones above are complete. Also this one could be closed too once the others are cleaned up :)

**Comment by chadlwilson** [comment]
Thanks.

Where was #204 addressed? Rightly or wrongly, #199 was re-opened due to that issue, and there is https://github.com/getgauge/gauge-csharp-lib/pull/44 to try and address some aspect here.

There are also multiple issues with people claiming the current plugin is not stable: https://github.com/getgauge/gauge/issues/2628 - so something is not right here, which I suspect relates to the async support breaking things. There should at least be one issue that summarises that problem and how it manifests. :-/

I've closed a few, but can I request that you comment on the original issues so the participants can comment themselves, as the context is lost here?
