### ISSUE TITLE
Failed to start gauge API: Time out connecting to dotnet

### ISSUE THREAD

**Issue by RemiHoston** [getgauge/gauge-dotnet#241]
**Is your feature request related to a problem? Please describe.**

When run the command
gauge run specs
the error happened
`Failed to start gauge API: Time out connecting to dotnet`

**Describe the solution you'd like**
Have found this issue occurred very frequently when running on local machine and pipeline agent. When it happened locally I can close the process from the Task Manager, but on pipeline have to retry after a few minutes. So I realized it may be a feature defect in the gauge main logic.

**My gauge version is:**
```
 Gauge version: 1.6.9
Plugins
-------
 csharp (0.10.6)
 dotnet (0.7.2)
 html-report (4.3.1)
 screenshot (0.3.0)
 xml-report (0.5.1)
```

**Describe alternatives you've considered**
It's better to close all the dotnet process when the gauge run command finished.

**Comment by jensakejohansson** [comment]
If I understand you correctly this happens occasionally? I can just mention that I have seen this problem from time to time for a long time (years). On my own development machine not very often, but on when working on a client's laptop I get it a couple of times every day I believe (should maybe start to track this more). 

I believed it to be a performance issue. When running larger projects on machines that are a little slow (for lack of a better description) Gauge tends be more unstable. I've also seen the problem i VSC that run/debug options does not appear - the project does not load correctly. Changing to a more powerful machine solved that issue.

I have had the timeout problem in pipelines too (Azure Linux agents), I "solved" it there by increasing the timeouts to some insane amount, since it only happend every now and then and a bigger timeout "solved" it.

gauge config --list (to see timeout options).

Unfortunately I'm too busy with customer project (I'm a consultant) to investigate, so I can only give vague statements, but in my opinion there is some flakeyness going on that should be addressed.

**Comment by mpekurny** [comment]
I have also seen this issue for a few years, but exclusively running through VSCode. I had always assumed that it may have been a defect in the VSCode plugin. The fix (for me) was to shut down VSCode and then kill all running processes of .NET Host. Reading through this thread, maybe it's a problem where the dotnet plugin isn't getting shut down correctly leaving running processes of .NET Host hanging around until the machine's limitations (memory/cpu) can no longer launch the next .NET Host in a timely manor. It's also possible the async changes have somehow made the existing issue worse, such as consume more resources per run or make it more likely it fails the shut down correctly.

**Comment by sriv** [comment]
Like Chad said, this can happen for a variety of reasons, but ultimately the error occurs when gauge is not able to connect to the dotnet plugin. The most likely cause is that the dotnet runner crashed for some reason.

Some options to get more details:

1. run with `--log-level=debug`, ex- `gauge run specs -log-level debug` -> this shows more information than normal and can shed some light on what's happening.
2. look for the details in the `logs` directory post the error. 
3. look at your windows event log under the "Application" category. 
4. if none of the above give enough hints - try invoking the dotnet plugin manually 
    a. locate the gauge plugins directory (by default these are in `%APPDATA%/gauge/plugins/dotnet/<version>` IIRC)
    b. now cd into your project directory and invoke dotnet plugin standalone
   
ex:
```
cd c:\path\to\project\root
%APPDATA%\gauge\plugins\dotnet\<version>\bin\dotnet.bat --start
```

This is the command that gauge invokes, so by manually invoking this you can see the stdout of gauge-dotnet when running your project. My suspicion is that something is going wrong here, and we will know more once we simulate the error.

As for the orphan processes, unfortunately in windows the child process does not die when gauge is killed forcibly. I suspect that is causing this behaviour but it's hard to comment without having a way to replicate the issue.

**Comment by RemiHoston** [comment]
Thank you guys!
Have run like this
> gauge run specs -l debug
But nothing useful can be output. 
On the other hand, I found that it is more often in the afternoon than in the morning and the total time consuming for the Gauge-Test-Task is about 48 sec. It seems to be related with the agent resources(CPU usage or disk). So I try to update the `runner_connection_timeout` (gauge.properties) from 30 sec to 180 sec.
Will keep monitor for a long time.

**Comment by RemiHoston** [comment]
And keep monitor for these two days, the most time consuming for the gauge test runner to connect the dotnet api is 46s. And so far no more time out issue has happened. 
I think my issue has been fixed.
