### ISSUE TITLE
 Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:62438] cause: EOF

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-dotnet#36]
### Expected behavior
Gauge should run after incorporating System.Text.Encoding.CodePages

### Actual behavior
Gauge is not starting execution and throwing error message.

### Steps to reproduce
1. Create .Net Core project
2. Include EPPPlus.Core package from NuGet. Microsoft's System.Text.Encoding.CodePages is part of this package
3. Create any one step implementation
4. Run from command prompt using "gauge run specs"
5. Gauge throws below exception which looks like something in Gauge is conflicting with System.Text.Encoding.CodePages

  Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:62438] cause: EOF
Gauge.Dotnet.GaugeListener System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Gauge.Dotnet.Wrappers.AssemblyWrapper.LoadFrom(String location) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/Wrappers/AssemblyWrapper.cs:line 42
   at Gauge.Dotnet.AssemblyLoader.ScanAndLoad(String path) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 128
   at Gauge.Dotnet.AssemblyLoader..ctor(IAssemblyWrapper assemblyWrapper, IEnumerable`1 assemblyLocations, IReflectionWrapper reflectionWrapper) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 43
   at Gauge.Dotnet.MessageProcessorFactory.GetProcessor(MessageType messageType, Boolean scan) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/MessageProcessorFactory.cs:line 50
   at Gauge.Dotnet.GaugeListener.PollForMessages() in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/GaugeListener.cs:line 56
Successfully generated html-report to => C:\Users\mghai\Desktop\Gauge\Thamo\Framework\reports\html-report\index.html
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 876ms

### Gauge version
Gauge version: 1.0.2
Commit Hash: b4288bb

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by BugDiver** [comment]
@manavghaigithub This issue is happening because `.Net core` could not load two different versions of same DLL.
The package `EPPPlus.Core` which you are trying to add uses `v4.4.0` of `System.Text.Encoding.CodePages` but the `.Net .core` runtime uses `v4.1.0.0`. So when the runner tries to load the project's assemblies it fails because some other version of the assembly is already loaded.

`.Net core` also does not support creating app domain's so the `gauge-dotnet` cannot load two versions of an assembly. It also does not support assembly redirection using `assemblyBinding`/`bindingRedirect`.

If you just want to use `System.Text.Encoding.CodePages`, as a workaround you can add the same version as the runtime in your project.

Example: `dotnet add package System.Text.Encoding.CodePages --version=4.1.0.0`

Also I see that the package `EPPPlus.Core` is not maintained, the github repo has been archived by the author.

**Comment by BugDiver** [comment]
@manavghaigithub Closing this since I don't think there is anything which can be done.
Please feel free to reopen if you think it's worth it.

**Comment by manavghaigithub** [comment]
Vinay  - Would it be possible to update this DLL in Gauge’s .net core runtime engine? For now We were able to make it to work by downgrading dll that comes with EPPPlus.

I think Gauge should always update system/Microsoft dll’s whenever available, otherwise users will get these problems as Gauge is adapted by more people. Please advise.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BugDiver** [comment]
I agree, but I think it's a limitation with the language.
AFAIK It does not provide a way to load an already loaded DLL.
This can be done `.Net Framework` (not core) using `AppDomain`. `.Net Core` does not provide a way to create separate AppDomain.
I might be wrong since I don't have a very deep knowledge of `.Net` world.

/cc @sriv

**Comment by manavghaigithub** [comment]
Hey Vinay - Who from Gauge team can look into this and put in the solution. As far as I understand the fix is to put latest .net System files in Gauge engine and this can be done only by Gauge team.


Thanks,
Manav Ghai

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BugDiver** [comment]
@manavghaigithub  The `gauge-dotnet` does not use `System.Text.Encoding.CodePages` directly, I guess it is used by the `.net core`  runtime itself.
I will investigate further and let you know if something can be done from our end.

**Comment by manavghaigithub** [comment]
Thanks Vinay. I thought Gauge is having the older version of this DLL but that’s weird to say .Net runtime is not updated. Yes please run it through your team and in the mean time I will also run it through my .Net experts to see if they can throw some light.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
